"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AVAILABLE_COMPONENTS = void 0;
// src/components.ts
exports.AVAILABLE_COMPONENTS = [
    'accordion',
    'alert-dialog',
    'alert',
    'aspect-ratio',
    'avatar',
    'badge',
    'button',
    'calendar',
    'card',
    'carousel',
    'checkbox',
    'collapsible',
    'combobox',
    'command',
    'context-menu',
    'dialog',
    'dropdown-menu',
    'form',
    'hover-card',
    'input',
    'label',
    'menubar',
    'navigation-menu',
    'popover',
    'progress',
    'radio-group',
    'scroll-area',
    'select',
    'separator',
    'sheet',
    'skeleton',
    'slider',
    'switch',
    'table',
    'tabs',
    'textarea',
    'toast',
    'toggle',
    'tooltip'
];
